blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/yourusername/scriptoris/blob/main/README.md
    about: Read the project documentation
  - name: 💬 Discussions
    url: https://github.com/yourusername/scriptoris/discussions
    about: Ask questions and discuss features with the community