blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/yourusername/scriptoris/discussions
    about: Ask questions and discuss with the community
  - name: Security Issues
    url: https://github.com/yourusername/scriptoris/security/advisories
    about: Report security vulnerabilities privately