name: 💡 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below with as much detail as possible.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief description of the feature you'd like to see
      placeholder: What feature would you like to see added?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this feature be useful? What problem does it solve?
      placeholder: |
        - As a user, I want to...
        - This would help with...
        - Currently I have to...
    validations:
      required: true

  - type: textarea
    id: detailed_description
    attributes:
      label: Detailed Description
      description: Provide a detailed description of how this feature should work
      placeholder: |
        Describe the feature in detail:
        - How should it behave?
        - What should the user interface look like?
        - How should it integrate with existing features?
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would be used
      placeholder: |
        Example usage scenarios:
        1. User opens editor and...
        2. User presses key combination...
        3. User sees...

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low (simple addition)
        - Medium (moderate changes required)
        - High (major feature requiring significant work)
        - Not sure

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Are there alternative solutions or workarounds you've considered?
      placeholder: |
        - Alternative approach 1: ...
        - Alternative approach 2: ...
        - Current workaround: ...

  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Any references to similar features in other editors or applications?
        Links to documentation, examples, or inspiration?
      placeholder: |
        - Similar feature in Editor X: [link]
        - Documentation: [link]
        - Example: [link]

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: This feature aligns with Scriptoris's goals as a terminal-based Markdown editor
          required: true
        - label: I would be willing to help implement this feature
          required: false